### ISSUE TITLE
Remove vendor scripts from lint

### ISSUE THREAD

**Issue by furzeface** [cartridge/cartridge-javascript#7]
# Project version:
**v0.4.0** 

type:
- [x] Bug

---

Currently vendor scripts get linted too, which is **bad**: https://github.com/cartridge/cartridge-javascript/blob/develop/_config/task.scripts.js#L12

**Comment by tawashley** [comment]
This is fixed in the multiple files PR
https://github.com/cartridge/cartridge-javascript/pull/6
I have assigned you to it, if you could have a look when you're able to.
